/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatHistory: typeof import('./components/ChatHistory.vue')['default']
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    EditModeSwitch: typeof import('./components/EditModeSwitch.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FeatureShowcase: typeof import('./components/FeatureShowcase.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageUploader: typeof import('./components/ImageUploader.vue')['default']
    ResultDisplay: typeof import('./components/ResultDisplay.vue')['default']
    UsageTips: typeof import('./components/UsageTips.vue')['default']
  }
}
