# AI图片生成应用配置文件

# 目录配置
directories:
  static: "static"
  generated_images: "static/generated_images"
  logs: "logs"

# 日志配置
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

# API配置
api:
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent"
  key_env_var: "GOOGLE_API_KEY"

# 图片处理配置
image_processing:
  max_width: 1024
  max_height: 768
  format: "JPEG"

# 生成配置
generation:
  temperature: 0.9
  top_p: 1
  top_k: 32
  max_output_tokens: 2048
  response_modalities: ["Text", "Image"]

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8000
  cors:
    allow_origins: ["*", "http://localhost:8080"]
    allow_credentials: true
    allow_methods: ["*", "GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*", "Content-Type", "Authorization", "X-Requested-With"] 